version: '2'
services:

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/html
    ports:
      - "8080:80"

  fpm:
    build: ./docker/fpm
    volumes:
      - ./source:/var/www/html
    ports:
      - "9000"

  postgres:
    image: postgres:alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
