version: '3'
services:

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/vhosts:/etc/nginx/conf.d
      - ..:/var/www/html
    ports:
      - "80:80"

  fpm:
    build: ./docker/fpm
    volumes:
      - ./docker/fpm/php.ini:/etc/php7/php.ini
      - ./docker/fpm/zzz-custom.conf:/etc/php7/php-fpm.d/zzz-custom.conf
      - ./docker/fpm/info:/var/www/info
      - ..:/var/www/html
    ports:
      - "9000"

  postgres:
    image: postgres:alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
