version: '3'
services:

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/vhosts:/etc/nginx/conf.d
      - ..:/var/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "fpm"
    working_dir: "/var/www"

  fpm:
    build: ./docker/fpm
    volumes:
      - ./docker/fpm/php.ini:/etc/php7/php.ini
      - ./docker/fpm/zzz-custom.conf:/etc/php7/php-fpm.d/zzz-custom.conf
      - ./docker/fpm/info:/var/www/info
      - ./docker/fpm/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./docker/fpm/logs/xdebug.log:/tmp/xdebug.log
      - ..:/var/www
    ports:
      - "9000"
    working_dir: "/var/www"

  cli:
    build: ./docker/cli
    env_file: .env
    volumes:
      - ./docker/cli/php.ini:/etc/php7/php.ini
      - ./docker/cli/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./docker/cli/logs/xdebug.log:/tmp/xdebug.log
      - ./docker/cli/info:/var/www/info
      - ..:/var/www
    user: "1000"
    working_dir: "/var/www"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
